packages:
  - "packages/*"

catalog:
  # TypeScript
  typescript: "^5.9.3"
  "@tsconfig/node22": "^22.0.5"
  "@tsconfig/strictest": "^2.0.8"
  "@types/node": "^25.5.0"
  # ESLint
  eslint: "^10.0.3"
  "@eslint/js": "^10.0.1"
  typescript-eslint: "^8.57.0"
  eslint-config-prettier: "^10.1.8"
  # Formatting
  prettier: "^3.8.1"
  # Testing
  vitest: "^4.1.0"
  "@vitest/coverage-v8": "^4.1.0"
  # Build / Dev
  rimraf: "^6.1.3"
  nodemon: "^3.1.14"
  "@swc/core": "^1.15.18"
